### ISSUE TITLE
Gurobi license :(

### ISSUE THREAD

**Issue by evancasey** [ivanpuhachov/line-drawing-vectorization-polyvector-flow#2]
Hi! Thank you for all the great work on this project.

I'm interested in using this work to generate a large dataset of vector line drawings for sketch-based deep learning research.

However, I currently can't use this tool because I don't have a Gurobi license and don't have access to an academic network at the moment to acquire an academic license.

Is it possible to provide a pre-built version of the tool or remove the dependency on Gurobi?

**Comment by ivanpuhachov** [comment]
Hi @evancasey, thanks for your interest!

Pre-built version might work, describe your platform and I will try to help you with that.

In the meantime, you can try PolyVectorization (https://github.com/bmpix/PolyVectorization) which does not have gurobi dependency.

Since you want to get a dataset of line drawings, maybe the dataset we used for training is what you are looking for. We took Google QuickDraw and Facebook CreativeBirds vector drawings and rasterized them with adobe illustrator. This approach is way faster than collecting raster drawings and vectorizing them. 
Dataset repo: https://github.com/ivanpuhachov/line-drawing-vectorization-polyvector-flow-dataset
Example: 
<img width="1095" alt="image" src="https://github.com/ivanpuhachov/line-drawing-vectorization-polyvector-flow/assets/49251289/691eb49f-6823-4f22-b864-81cc1451e71a">

**Comment by evancasey** [comment]
I've attained a Gurobi license actually so I think we're all good! Will report back with the results :)
